### ISSUE TITLE
Different temp directory

### ISSUE THREAD

**Issue by IAmNotAkib** [luvyana/Piana#11]
So, by default piana uses `%temp%` directory to store temp files. And my ssd is running out of space where the `%temp%` directory is located. How can i change it. And also it has 18GB+ space left before importing map. But after importing map it had 0 bytes free space. I deleted everything inside `%temp%` and `temp` folder and got 5GB free so far. What to do now...

**Comment by Devostated** [comment]
Piana has an Export Folder setting and a "At least 30+ gb of empty space." requirement for a reason.
Maybe try restarting PC to get rid of some temporary files.

**Comment by floxay** [comment]
Can't repro, `%temp%` is fine for me and that's most likely be some Blender auto saving feature, also unsure what `temp` refers to.
