### ISSUE TITLE
I can't see the "Map Importer" panel.

### ISSUE THREAD

**Issue by Reffex1** [luvyana/Piana#23]
So, i enable Piana on Add-ons menu (while Toogle System Console opened). And i select the paths correctly, but i can't see the "Map Importer Panel" or i don't know where to find it. Please help me about it. Thanks.

**Comment by luvyana** [comment]
Usually this is fixed by clicking the paths edit boxes once, which forces addon to re check the paths and reveal the panel.

**Comment by Reffex1** [comment]
> Usually this is fixed by clicking the paths edit boxes once, which forces addon to re check the paths and reveal the panel.

It was my fault, i didn't look at the N panel sorry about that :)
