### ISSUE TITLE
Problems with importing map

### ISSUE THREAD

**Issue by S0n3w4yM** [luvyana/Piana#28]
I have problem with importing: when im trying to import map, it stops working in like 2 seconds and here is what i see in console/ Version i tried: 3.5, 3.1. What did I do wrond?
![изображение_2023-04-06_215445652](https://user-images.githubusercontent.com/130084331/230445188-74f8a922-7d7e-44f3-9cba-05e341664686.png)
![изображение_2023-04-06_215457273](https://user-images.githubusercontent.com/130084331/230445232-72ea3a4c-89a1-4460-87d0-f2b6f3f824c3.png)

**Comment by JohWeak** [comment]
same =/ 
did you find a solution?

**Comment by JohWeak** [comment]
I just downloaded Blender from steam so it works for now
