### ISSUE TITLE
Imports nothing

### ISSUE THREAD

**Issue by prufaraSS** [luvyana/Piana#31]
![image](https://user-images.githubusercontent.com/19390500/233800045-25274b04-ddf6-4a94-8609-8f2a8c0103a9.png)

tried out all checks it imports not a single vertex, face nor model
json file:

![image](https://user-images.githubusercontent.com/19390500/233800127-b652575e-1d98-4bd2-952e-4c72e5d979cb.png)

**Comment by KaiserM21** [comment]
This information does not help, can you send a screenshot of the Blender console? Also please make sure you have installed the perquisites. And after an unsuccessful export, delete everything in the export folder before trying again! 👍

**Comment by prufaraSS** [comment]
Found out, that I haven't installed installed .NET (I'm pretty sure that .NET is installed but not reqired version), for those who also have same issue, check the first few lines of console output, there must be a line which says application requires .NET, but don't download the version from link this console gives, it doesn't work. Download only from link listed in README.
