### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Jenniieee** [luvyana/Piana#32]
I downloaded Piana but in Blender, it keeps saying fake_ module: addon missing "bl_info".
Please help

**Comment by KaiserM21** [comment]
It means something went wrong when you installed the addon. Make sure you downloaded the release zip and installed it directly. You can also follow a tutorial online, there is plenty of them

**Comment by KaiserM21** [comment]
If the "fake_ module: addon missing "bl_info"" persists, delete any unwanted files from C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons

**Comment by Jenniieee** [comment]
What do i delete from the C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons, blender keeps saying missing bl_info.

**Comment by Jenniieee** [comment]
Never mind i got it! thanks for the help
