### ISSUE TITLE
Cannot Import Add-on to Blender

### ISSUE THREAD

**Issue by ATex0910** [luvyana/Piana#33]
Hey, I'm encountering an issue while attempting to import this add-on into Blender. Despite multiple attempts, including trying an older version, I am still unsure about what I do wrong. Currently, I'm using Blender 3.4.1. Please help!

<img width="780" alt="Screenshot 2023-06-28 at 7 39 23 pm" src="https://github.com/luvyana/Piana/assets/138001995/2fa4a2be-e5db-435c-bd80-975c39e0a188">

**Comment by Devostated** [comment]
It's windows only as of now
