### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by Matitron** [luvyana/Piana#34]
Hello, sorry if this is a known issue or just not a feature but all the maps I've extracted have not had any lighing from the map it's self, the sky is there and all but the interior of buildings and such is dark and lacks lighting

**Comment by KaiserM21** [comment]
Light import is supported, you just have to enable it 👍

**Comment by rickyfx18** [comment]
They are enabled but still doesn't work! Same issue!

**Comment by KaiserM21** [comment]
> They are enabled but still doesn't work! Same issue!

It works fine, you obviously have to disable any blocking meshes and use cycles rendered view...
