### ISSUE TITLE
"Map Importer" empty

### ISSUE THREAD

**Issue by xNoobyyy** [luvyana/Piana#5]
Blender Version: 3.1.2
Followed all instructions!
![image](https://user-images.githubusercontent.com/71840441/172236410-5b81e0ea-7a00-41b1-91b7-67a850eaef91.png)

**Comment by coreartz** [comment]
press on the PAKs folder path and press enter.

**Comment by luvyana** [comment]
@xNoobyyy 
Left click those folder path inputs, and press enter them to refresh. (Do for both) 

Also do not use "Debug Mode" if you don't know what you are doing.
